name: bill
description: A new Flutter project.
version: 0.8.6+38

environment:
  sdk: ">=2.12.0 <3.0.0"
#Plugin Dependencies
dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.0
  dio: ^4.0.0
  equatable: ^2.0.0
  fancy_on_boarding: ^1.7.0
  flutter_bloc: ^7.0.0
  intro_views_flutter: ^3.1.0
  mobile_number: ^1.0.4
  pin_code_fields: ^7.1.0
  provider: ^5.0.0
  random_string: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  freezed: ^0.14.0
  json_serializable: ^4.1.0

#Assets
flutter:
  uses-material-design: true
  # Image Assets
  assets:
    - images/
    - images/bingkai.png
  # Fonts Assets
  fonts:
    - family: Young
      fonts:
        - asset: fonts/young.ttf
        - asset: fonts/young italic.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.otf
        - asset: fonts/Montserrat-BlackItalic.otf
        - asset: fonts/Montserrat-Bold.otf
        - asset: fonts/Montserrat-BoldItalic.otf
        - asset: fonts/Montserrat-ExtraBold.otf
        - asset: fonts/Montserrat-ExtraBoldItalic.otf
        - asset: fonts/Montserrat-ExtraLight.otf
        - asset: fonts/Montserrat-ExtraLightItalic.otf
        - asset: fonts/Montserrat-Italic.otf
        - asset: fonts/Montserrat-Light.otf
        - asset: fonts/Montserrat-LightItalic.otf
        - asset: fonts/Montserrat-Medium.otf
        - asset: fonts/Montserrat-MediumItalic.otf
        - asset: fonts/Montserrat-Regular.otf
        - asset: fonts/Montserrat-SemiBold.otf
        - asset: fonts/Montserrat-SemiBoldItalic.otf
        - asset: fonts/Montserrat-Thin.otf
        - asset: fonts/Montserrat-ThinItalic.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
