name: bill
description: A new Flutter project.
version: 1.0.1+40
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  animations: ^2.0.0
  intro_slider: ^3.0.2
  bloc: ^7.0.0
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  dio: ^4.0.0
  equatable: ^2.0.2
  fancy_on_boarding: ^1.7.0
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  flutter_bloc: ^7.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^6.0.0
  flutter_markdown: ^0.6.2
  flutter_native_splash: ^1.2.0
  flutter_styled_toast: ^2.0.0
  get: ^4.1.4
  http: ^0.13.3
  image_picker: ^0.8.0+1
  intl: ^0.17.0
  intro_views_flutter: ^3.1.1
  json_serializable: ^4.1.3
  numeric_keyboard: ^1.1.0
  lottie: ^1.0.1
  mobile_number: ^1.0.4
  money_formatter: ^0.0.3
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.2.0
  pinput: ^1.2.0
  provider: ^5.0.0
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0
  random_string: ^2.2.0-nullsafety
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  mocktail: ^0.1.0

flutter_native_splash:
  background_image: "assets/images/billnew.png"
  fullscreen: true
  # color: "#42a5f5"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Young
      fonts:
        - asset: assets/fonts/young.ttf
        - asset: assets/fonts/young italic.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.otf
        - asset: assets/fonts/Montserrat-BlackItalic.otf
        - asset: assets/fonts/Montserrat-Bold.otf
        - asset: assets/fonts/Montserrat-BoldItalic.otf
        - asset: assets/fonts/Montserrat-ExtraBold.otf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.otf
        - asset: assets/fonts/Montserrat-ExtraLight.otf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.otf
        - asset: assets/fonts/Montserrat-Italic.otf
        - asset: assets/fonts/Montserrat-Light.otf
        - asset: assets/fonts/Montserrat-LightItalic.otf
        - asset: assets/fonts/Montserrat-Medium.otf
        - asset: assets/fonts/Montserrat-MediumItalic.otf
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-SemiBold.otf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.otf
        - asset: assets/fonts/Montserrat-Thin.otf
        - asset: assets/fonts/Montserrat-ThinItalic.otf
